Return-Path: <linux-pm-owner@vger.kernel.org>
X-Original-To: lists+linux-pm@lfdr.de
Delivered-To: lists+linux-pm@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id DC38771CE2
	for <lists+linux-pm@lfdr.de>; Tue, 23 Jul 2019 18:27:26 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S2388107AbfGWQ1Z (ORCPT <rfc822;lists+linux-pm@lfdr.de>);
        Tue, 23 Jul 2019 12:27:25 -0400
Received: from mail-ot1-f67.google.com ([209.85.210.67]:40782 "EHLO
        mail-ot1-f67.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1732689AbfGWQ1Z (ORCPT
        <rfc822;linux-pm@vger.kernel.org>); Tue, 23 Jul 2019 12:27:25 -0400
Received: by mail-ot1-f67.google.com with SMTP id 60so5099036otr.7
        for <linux-pm@vger.kernel.org>; Tue, 23 Jul 2019 09:27:24 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=android.com; s=20161025;
        h=mime-version:references:in-reply-to:from:date:message-id:subject:to
         :cc;
        bh=BWnTq6sVUPE744CYWkesDiko8LlbFzFljIJsRGuRDoY=;
        b=NpoaCCr8INRs+7BK5AitJJ0kbuQvoQh3fz1aGPtnvdfsxKObDYYwEkx3kVZw1Spuh0
         JZgZqqjS/vX2IhIy7B8u6HJWlB/DsuIx7JIJiWbfaTmB4Qkbej6ikXZLm1VckJyrLrX8
         2qmOZGuT6zBIk9jhPniMCpQp5A+Q+B91o+GLTvbrcw9aHsW01HbX5JyLeq2ZU4F0WwWc
         kScBVrA58334W7JEw7SgN1q2vT5XEEEYKOBYqNaCB38qaJXmwqV1eBKZISclvi1AVL+C
         rUwB9qvVOxDSc7SjcxWHoEl2VQ7DqHbFXrdgs/gCO1SMPqZ04GrywW5z/ODSD3SrMNPN
         QKXw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:references:in-reply-to:from:date
         :message-id:subject:to:cc;
        bh=BWnTq6sVUPE744CYWkesDiko8LlbFzFljIJsRGuRDoY=;
        b=M/1oLVaEfzufHlC2JeMaIV+4kc77V2QaRKYAAMtf+FGwalAOYHj7cncXeK8p8orqhQ
         nnZ3d4QgXqyEplRIXL6XsWUYphVzAjdGGu2GenZg7F/nz7ZtFtzHdcUtYzyjS8rZuZrZ
         p0q+PNwDhv4dyixZ8T/CX4xwdxSbl/XFHnWl7qsKbJW8i+uGA8PTF5T7mOriGhSq+B17
         aV4Zlpo2ceMJOeuX1rC9DRqd/EG/LCT+hTIhcHIrfQr6Gkbmr1g593GbcBNehfrZWoZs
         SYPeP9s5Mmr4JM7nVRzyiGP6ECu9Zco1ciPQ5wimlGCQCAvt47PU4Agn43C/bhA4G/ma
         yWkg==
X-Gm-Message-State: APjAAAVAHiT3nNyV3fQXlRzbYuAmLxUOscSs8vv3/sijbIRhOVwJBf5b
        QVvoIB7tXS1zDC97eiXXKMx4qT65Zp6RgWGciBo=
X-Google-Smtp-Source: APXvYqwfTZRwYWVOLPJZSn89VK1eY1HD9mYuFULKWYonSgGD6kKY/GHz/3FXb745PFr5VcvAaYpVGJpSRCkhIf3PGQw=
X-Received: by 2002:a9d:5f02:: with SMTP id f2mr57099525oti.148.1563899244290;
 Tue, 23 Jul 2019 09:27:24 -0700 (PDT)
MIME-Version: 1.0
References: <201907232235.iRDGgF0x%lkp@intel.com> <20190723140337.GA54192@lkp-kbuild04>
In-Reply-To: <20190723140337.GA54192@lkp-kbuild04>
From:   Tri Vo <trong@android.com>
Date:   Tue, 23 Jul 2019 09:27:13 -0700
Message-ID: <CANA+-vCDTSvfeD8upBfpUP5aSpM7cUqT8xB0URRwkhZ1Gqr+qQ@mail.gmail.com>
Subject: Re: [PATCH] PM / wakeup: fix ptr_ret.cocci warnings
To:     kbuild test robot <lkp@intel.com>
Cc:     kbuild-all@01.org, linux-acpi@vger.kernel.org, devel@acpica.org,
        Linux PM <linux-pm@vger.kernel.org>,
        "Rafael J. Wysocki" <rjw@rjwysocki.net>,
        Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Content-Type: text/plain; charset="UTF-8"
Sender: linux-pm-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-pm.vger.kernel.org>
X-Mailing-List: linux-pm@vger.kernel.org

On Tue, Jul 23, 2019 at 7:03 AM kbuild test robot <lkp@intel.com> wrote:
>
> From: kbuild test robot <lkp@intel.com>
>
> drivers/base/power/wakeup_stats.c:143:1-3: WARNING: PTR_ERR_OR_ZERO can be used
>
>
>  Use PTR_ERR_OR_ZERO rather than if(IS_ERR(...)) + PTR_ERR
>
> Generated by: scripts/coccinelle/api/ptr_ret.cocci
>
> Fixes: 0b050f7fb8a1 ("PM / wakeup: show wakeup sources stats in sysfs")
> CC: Tri Vo <trong@android.com>
> Signed-off-by: kbuild test robot <lkp@intel.com>

Reviewed-by: Tri Vo <trong@android.com>

> ---
>
> tree:   https://kernel.googlesource.com/pub/scm/linux/kernel/git/rafael/linux-pm.git bleeding-edge
> head:   14b99dcec44e7bca9f01e042002f57e9f0dda133
> commit: 0b050f7fb8a1e45c72ca945bac2821a59d4a0101 [21/23] PM / wakeup: show wakeup sources stats in sysfs
>
>  wakeup_stats.c |    5 +----
>  1 file changed, 1 insertion(+), 4 deletions(-)
>
> --- a/drivers/base/power/wakeup_stats.c
> +++ b/drivers/base/power/wakeup_stats.c
> @@ -140,10 +140,7 @@ EXPORT_SYMBOL_GPL(wakeup_source_sysfs_re
>  static int __init wakeup_sources_sysfs_init(void)
>  {
>         wakeup_class = class_create(THIS_MODULE, "wakeup");
> -       if (IS_ERR(wakeup_class))
> -               return PTR_ERR(wakeup_class);
> -
> -       return 0;
> +       return PTR_ERR_OR_ZERO(wakeup_class);
>  }
>
>  postcore_initcall(wakeup_sources_sysfs_init);
